service:
  name: karin-fujiyoshi-info-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  memorySize: 256
  timeout: 10

functions:
  rss-blog:
    handler: src/handler.rssBlog
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http:
          method: get
          path: rss/blog
  rss-news:
    handler: src/handler.rssNews
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http:
          method: get
          path: rss/news
