service:
  name: karin-fujiyoshi-info-bot

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1

functions:
  rss-blog:
    handler: src/handler.rssBlog
    role: ${env:AWS_LAMBDA_IAM_ROLE}
    events:
      - http:
          method: get
          path: rss/blog
